### ISSUE TITLE
Add process to transform "incomplete" OTS proofs to complete proofs

### ISSUE THREAD

**Issue by katelynsills** [starlinglab/uwazi-hyperbee-prototype#23]
Currently, the OTS proofs are "incomplete" meaning that the proof does not include anchoring on the Bitcoin blockchain. That takes time (perhaps 6 to 15 hours), so we need a separate process to go through and retrieve the complete proofs and add them to the Hyperbee instance.

**Comment by makew0rld** [comment]
It's more on the level of hours than minutes. Each calendar server lists "Average time between transactions in the last week". As an example, the lowest currently is 3.5 hours, and the highest is 15.27.

**Comment by katelynsills** [comment]
> It's more on the level of hours than minutes. Each calendar server lists "Average time between transactions in the last week". As an example, the lowest currently is 3.5 hours, and the highest is 15.27.

Are we sure that "time between transactions" isn't the time between requests? The incomplete file says "waiting on Bitcoin confirmation" and the merkle tree is already created at that point, so no more hashes would be added to that submission. It'd be very strange for calendars to wait for no reason before submitting a bitcoin transaction if they can't add new hashes. 

I think an incomplete file can be completed as soon as the Bitcoin transaction is confirmed. The [documentation](https://github.com/opentimestamps/opentimestamps-client/blob/master/README.md#usage) says: "It takes a few hours for the timestamp to get confirmed by the Bitcoin blockchain; we're not doing one transaction per timestamp."

**Comment by makew0rld** [comment]
> the merkle tree is already created at that point, so no more hashes would be added to that submission

My understanding is this is not correct. More hashes are added before making a Bitcoin transaction.

>  what the aggregation system actually does is aggregates all submitted timestamps in a one second interval into a merkle tree, and submits the tip of that tree - which we call a “commitment” - to a public calendar server. - [Source](https://petertodd.org/2016/opentimestamps-announcement)

This one-second interval is what allows the stamping process to only take a second. But the commitments are not submitted as an individual transaction every second, as that would be expensive. Commitments are collected and then submitted altogether, possibly forming another merkle tree. For example looking at the [bob server](https://bob.btc.calendar.opentimestamps.org/) right now, there are over 700 pending commitments. And looking at the server [source code](https://github.com/opentimestamps/opentimestamps-server/blob/master/otsd#L82-L84) we can see there is a minimum interval between timestamp transactions, set to a default of 6 hours.

So my understanding is that the time to when timestamps can be confirmed on chain is determined by the following:

`btc-min-tx-interval` (and we don't know if the calendars are using the default) \
\* [randomness](https://github.com/opentimestamps/opentimestamps-server/blob/master/otsserver/stamper.py#L367-L370) (up to x2 original interval) \
\+ bitcoin delays of adding a block (which is about an hour I think based on current fees used by the cal server)

Finally, if you look at the confirmed transaction list on the [bob server](https://bob.btc.calendar.opentimestamps.org/) you can see the delays between them are large, about 9 hours between the most recent two transactions.

**Comment by katelynsills** [comment]
Gotcha, thanks for looking this up! 

> My understanding is this is not correct. More hashes are added before making a Bitcoin transaction.

I was interpreting the "prepend" & "append" values in the incomplete ots file to be merkle tree proofs. 

```
katesills@kates-mbp proofs % ots info 21ded3b14a5f3a400f08e14b8118e5d41ce66cc01fc106f577363e5c8f569311-meta-content.json.ots
File sha256 hash: e40f38c3c1a2ca9e369bca1e156b6214c3586edee8a8755dac74150b53a0dde4
Timestamp:
append 020ffdec192f5f45009480472b67c608
sha256
 -> append 07adeb917415a5be75857a4fafc01184
    sha256
    prepend 629fc238
    append 3a350ecbdd3429e0
    verify PendingAttestation('https://finney.calendar.eternitywall.com')
 -> append 6b7d29ee0b8e69d461632be498d807d2
    sha256
    prepend 629fc238
    append be49eecaef7412d2
    verify PendingAttestation('https://alice.btc.calendar.opentimestamps.org')
```

If they are merkle tree proofs, then that means nothing more can be added to *that* merkle tree since any addition changes the root hash and thus changes the proof. But that merkle tree root could be the leaf value of another merkle tree - so that must be how it is done?

**Comment by makew0rld** [comment]
Yes, I think the merkle root that you can see just ends up being part of a larger tree. I'm not 100% sure on the details of this though.

**Comment by petertodd** [comment]
FYI in general it's fine to simply store non-upgraded OTS proofs. The public calendar infrastructure is designed to store and make available the rest of the data necessary to validate a non-upgraded proof indefinitely. You can also make your own backup of that data with the [otsd-backup tool](https://github.com/opentimestamps/opentimestamps-server/blob/master/otsd-backup.py). OpenTimestamps works this way for the convenience of applications like git timestamping, where it isn't feasible to upgrade the proofs in place.

Of course, if your architecture can do this conveniently, by all means, go ahead!
