### ISSUE TITLE
Demo planning

### ISSUE THREAD

**Issue by benhylau** [starlinglab/uwazi-hyperbee-prototype#32]
## Set Up

1. Upload Uwazi Entity View page
    <img width="1366" alt="Screen Shot 2023-06-01 at 11 26 36 AM" src="https://github.com/starlinglab/uwazi-hyperbee-prototype/assets/2261308/35b37b97-4bd2-4d52-aa0f-79a9a86dbc4e">
2. Upload ReplayWeb service worker script, then ask Uwazi to update name of this file in the Uwazi database (later this should be done via Uwazi UI, this is necessary for WACZ to work)
    <img width="1368" alt="Screen Shot 2023-06-01 at 11 33 00 AM" src="https://github.com/starlinglab/uwazi-hyperbee-prototype/assets/2261308/db2e0440-3256-4c2b-94bc-beb159f7af72">
3. Copy `add_cid` script to Uwazi server and set up cron job to run

## Usage

1. Add trusted feeds
    <img width="618" alt="Screen Shot 2023-06-01 at 11 45 46 AM" src="https://github.com/starlinglab/uwazi-hyperbee-prototype/assets/2261308/a7791f61-501d-4c37-bd02-645d385911e0">
2. Upload file (WACZ, PDF, etc.) in Uwazi UI
    <img width="1375" alt="Screen Shot 2023-06-01 at 11 27 18 AM" src="https://github.com/starlinglab/uwazi-hyperbee-prototype/assets/2261308/06543bdf-86c3-42e3-b888-e538ae4bd3fe">
3. Explore attested attributes associated with CID that come from trusted feeds
    <img width="1367" alt="Screen Shot 2023-06-01 at 11 42 37 AM" src="https://github.com/starlinglab/uwazi-hyperbee-prototype/assets/2261308/295b71da-9207-43fe-a1b8-730881a42f4a">
4. Click into parent asset and see attested attributes of parent  asset (see list of derivative CIDs)
    <img width="1378" alt="Screen Shot 2023-06-01 at 11 47 34 AM" src="https://github.com/starlinglab/uwazi-hyperbee-prototype/assets/2261308/38a2329b-8911-455f-afed-b3fea7752d0f">
5. Click `Graph` button to see CID graph
    <img width="1370" alt="Screen Shot 2023-06-01 at 11 50 30 AM" src="https://github.com/starlinglab/uwazi-hyperbee-prototype/assets/2261308/9a85f359-e6fe-4377-b668-cc1c633aafad">

## Relationship types

In the `Graph` view we should see the following representation of edges:

- `children` and `parents` are represented the same, and arrows always go from a `parent` to a `child`
- the analyzed asset is in purple, whereas everything else is grey
- the graph depth is 3 levels
- edge colour is used to indicate the source of the relationship (show two sources)
- text on the edge tells how the two items are related

Vocabulary see https://www.notion.so/ADG3-Specification-of-schema-for-the-data-graph-and-vocabulary-to-describe-edges-bb518766c68b43ea97e0318ed3477370?pvs=4

**Comment by basilesimon** [comment]
3/4ths of the way through re-jigging the narrative a bit: https://app.mural.co/t/starlinglab7814/m/starlinglab7814/1686772110475/5729446bd4bec4471e31fd993f2e835f30d97752?sender=ub3a421c048efd7d270741703
