### ISSUE TITLE
Explore Value Types (Including Binary for Timestamp Proof)

### ISSUE THREAD

**Issue by katelynsills** [starlinglab/uwazi-hyperbee-prototype#4]
The values in our key-value store will have multiple types. For instance, the actual value is likely to be a UTF-8 string, but we also want to include the timestamp of the attestation and a signature, which would cause us to want to use JSON with 'timestamp' and 'signature' as keys in that JSON. Another complication is that our timestamping proof, if we use OpenTimestamps, is a binary .ots file, and we need to include that in the key-value store. 

We need to figure out how to best encode all of the information that we need to put in the key-value store, given what is available to us as options in Hyperbee/Hypercore.

## Methods

~~@RangerMauve's [HyperbeeDeeBee](https://github.com/RangerMauve/hyperbeedeebee/) uses BSON so if we use it, we might be able to avoid going to a low-level solution, like doing our own conversions. Let's start with HyperbeeDeeBee and see whether we hit any roadblocks. See [comment below](https://github.com/starlinglab/uwazi-hyperbee-prototype/issues/4#issuecomment-1487751068).~~

For right now, we cannot use HyperbeeDeeBee due to the AGPL license (Starling must use MIT). For this task, we would like to write a thin BSON wrapper around HyperBee such that our values can be read as json, utf-8, or binary as the need arises, but are all ultimately stored as binary, using the 'binary' HyperBee setting instance-wide. 

## Alternative approaches

We could embed knowledge of particular attribute types in the application itself (for instance, the timestamp proof is always just read as binary, but location is JSON). However, we want custom attestations to be added at will by different parties, and we don't necessarily want to rule out the idea that the same attribute could have different value types over time or between different HyperBee instances. So the more flexible, more self-describing, and less hard-coded, the better, although it is a trade-off given limited hours. 

## Background

From the [Hyperbee documentation](https://docs.holepunch.to/building-blocks/hyperbee#api):

Property | Description | Type | Default
-- | -- | -- | --
valueEncoding | Encoding type for the values. Takes values of 'json', 'utf-8', or 'binary'. | String | 'binary'
keyEncoding | Encoding type for the keys. Takes values of 'ascii', 'utf-8', or 'binary'. | String | 'binary'

From the [HyperCore documentation](https://docs.holepunch.to/building-blocks/hypercore#api):

Property | Description | Type | Default
-- | -- | -- | --
valueEncoding | one of 'json', 'utf-8', or 'binary' | String | 'binary'

**Comment by RangerMauve** [comment]
Yeah I would strongly advise using BSON instead of rolling new stuff or having to deal with custom JSON bits. In particular, using BSON means that you can sort stuff by date more easily with the built in indexing support.

**Comment by RangerMauve** [comment]
It might be worth it to store the "raw" OTS stuff in the document, but then add a Date property along side it so that you can index over it and perform range queries easily.

**Comment by katelynsills** [comment]
Thanks so much, @RangerMauve. I'll start with HyperbeeDeeBee then, and will let you know if we hit any roadblocks there! 

> It might be worth it to store the "raw" OTS stuff in the document, but then add a Date property along side it so that you can index over it and perform range queries easily.

This sounds like what we want ideally from a timestamping service - the timestamp date as a signed attestation just like any other property/value. None of the main existing timestamping services give this because they think it undermines the untrusted nature, but I think this is extremely helpful in addition to a proof. Not everyone wants or needs to follow the entire proof, just like not everyone needs to run their own Bitcoin node. It'd be nice if they did, but we all have limited resources.

Does that cover what you meant here, or is there something else too?

**Comment by makew0rld** [comment]
Just wanted to flag that hyperbeedee's AGPL license will conflict with our current MIT license for the repo.

**Comment by katelynsills** [comment]
@RangerMauve, is there any chance that hyperbeedee's license could change to be compatible with MIT?

**Comment by RangerMauve** [comment]
Hmm, I'm not sure TBH. Is MIT a hard requirement? I'd really like to avoid corpos coming in and close sourcing work behind paywalls and the such. 😅

**Comment by RangerMauve** [comment]
Since you aren't modifying the hyperbeedeebee source it might be enough to just link to it somewhere, right?

**Comment by benhylau** [comment]
Not really. We wouldn't be able to use it at all with AGPL. Many orgs have a policy of basically not taking any code that is AGPL bc of the risk to their existing codebase.

**Comment by katelynsills** [comment]
This was updated to using dag-cbor 2023-04-14 in this PR https://github.com/starlinglab/uwazi-hyperbee-prototype/pull/14
